[package]
name = "repl"
version = "0.1.0"
edition = "2024"

[dependencies]
remotro = { path = "../lib" }
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.11"
colored = "3.0.0"
